### PR TITLE
improvement on guide part

### PR DESCRIPTION
**Pull request by guncebektas**
add: description for guide
add: prepare to v3 link into the guide part, I think we should improve content related with migration

### CODE REVIEW

**Comment by guncebektas** [comment]
some companies that are using meteor.js have added

**Comment by jankapunkt** [comment]
@StorytellerCZ can you check what's the matter with the CI here? I think you know the config better than me

**Review by StorytellerCZ — APPROVED** [review]

**Comment by StorytellerCZ** [comment]
@guncebektas @jankapunkt fixed on main

**Comment by jankapunkt** [comment]
Some lint errors remain to be fixed, apart from that lgtm

**Comment by guncebektas** [comment]
how can I white-list new URLs? @StorytellerCZ @jankapunkt

**Comment by StorytellerCZ** [comment]
I think with Favro, TeamGrid and CheatCode links it doesn't like that it is going to the login page instead of the main one (or at least I don't like that).
In general when reffering to companies it should go to their main page instead of login page.

**Comment by StorytellerCZ** [comment]
With `https://longtailpro.com/` I get 522 error, so I think lint is complaining about that.

**Comment by guncebektas** [comment]
503 for twitter :)

**Pull request merged**
